# =============================================================================
# Pronoun resolution naturalness rating — analysis pipeline
# =============================================================================
# Generated by behavioral_api /admin/analysis bundle.
#
# How to run:
#   1. Unzip the bundle so `analysis.xlsx` and this file sit in the same folder.
#   2. Open `analysis.R` in RStudio and click Source — or run from a shell:
#        Rscript analysis.R
#   3. Plots are saved under `outputs/`. All tables print to the R console.
#
# Design: 3 (pronoun: pro / o / kendisi) x 2 (order: forward / cataphora)
#          x 2 (antecedent: subject / object) = 12 within-subject conditions.
# DV: naturalness rating, 1..7 Likert.
# =============================================================================

# ---------- 0. Packages ----------
required <- c("readxl", "dplyr", "tidyr", "ordinal", "lme4", "lmerTest",
              "emmeans", "ggplot2")
missing  <- setdiff(required, rownames(installed.packages()))
if (length(missing)) {
  message("Installing missing packages: ", paste(missing, collapse = ", "))
  install.packages(missing, repos = "https://cloud.r-project.org")
}
suppressPackageStartupMessages({
  library(readxl); library(dplyr); library(tidyr)
  library(ordinal); library(lme4); library(lmerTest)
  library(emmeans); library(ggplot2)
})

INPUT_XLSX <- "analysis.xlsx"
OUT_DIR    <- "outputs"
dir.create(OUT_DIR, showWarnings = FALSE)

# ---------- 1. Load + structure ----------
raw <- read_excel(INPUT_XLSX, sheet = "Long format")
cat("\n=== Loaded ===\n")
cat("Rows:", nrow(raw), " | Participants:", length(unique(raw$participant)), "\n")
cat("Columns:", paste(names(raw), collapse = ", "), "\n")
print(head(raw, 3))

# ---------- 2. Attention-check exclusions ----------
# Filler `correct_answer` interpretation:
#   TRUE  = natural anchor  -> participant should rate HIGH; misrate if rating <= 3
#   FALSE = broken anchor   -> participant should rate LOW;  misrate if rating >= 5
filler <- raw %>% filter(item_type == "filler", !is.na(correct_answer))
cat("\n=== Attention-check exclusions ===\n")
if (nrow(filler) > 0) {
  filler <- filler %>% mutate(
    misrate = (correct_answer == TRUE  & rating <= 3) |
              (correct_answer == FALSE & rating >= 5)
  )
  bad <- filler %>% group_by(participant) %>%
    summarise(n_misrated = sum(misrate, na.rm = TRUE), .groups = "drop") %>%
    filter(n_misrated > 3)
  if (nrow(bad) > 0) {
    cat("Excluding the following participants (>3 misrated attention checks):\n")
    print(bad)
    raw <- raw %>% filter(!participant %in% bad$participant)
  } else {
    cat("None excluded.\n")
  }
} else {
  cat("(No filler `correct_answer` labels available; skipping exclusions.)\n")
}

# Zero-variance / single-rating flag (does not auto-exclude — informational)
var_flag <- raw %>%
  filter(item_type == "critical") %>%
  group_by(participant) %>%
  summarise(sd = sd(rating, na.rm = TRUE), .groups = "drop") %>%
  filter(is.na(sd) | sd < 0.01)
if (nrow(var_flag) > 0) {
  cat("\nFLAG: zero/near-zero variance participants (consider excluding):\n")
  print(var_flag)
}

# Critical-only, typed factors
d <- raw %>%
  filter(item_type == "critical",
         !is.na(rating),
         !is.na(pronoun), !is.na(order), !is.na(antecedent)) %>%
  mutate(
    pronoun    = factor(pronoun,    levels = c("pro", "o", "kendisi")),
    order      = factor(order,      levels = c("forward", "cataphora")),
    antecedent = factor(antecedent, levels = c("subject", "object")),
    congruency = factor(congruency, levels = c("incongruent", "congruent")),
    rating_o   = ordered(rating, levels = 1:7),
    participant = factor(participant),
    item_id     = factor(item_id)
  )
cat("\nAfter exclusions: ", nrow(d), " critical rows / ",
    length(unique(d$participant)), " participants\n", sep = "")

# =============================================================================
# STEP 1 — DESCRIPTIVES (across participants)
# =============================================================================
desc <- function(df, ...) {
  df %>% group_by(...) %>%
    summarise(n = n(),
              mean = round(mean(rating), 2),
              sd   = round(sd(rating),   2),
              .groups = "drop")
}

cat("\n=== (a) All 12 cells ===\n")
print(desc(d, pronoun, order, antecedent), n = Inf)

cat("\n=== (b) Pronoun x Antecedent (collapse order) ===\n")
print(desc(d, pronoun, antecedent), n = Inf)

cat("\n=== (c) By pronoun ===\n")
print(desc(d, pronoun))

cat("\n=== (d) Forward vs cataphora ===\n")
print(desc(d, order))

cat("\n=== (e) Congruency, overall ===\n")
print(desc(d, congruency))

cat("\n=== (e) Congruency, within each pronoun ===\n")
print(desc(d, pronoun, congruency), n = Inf)

# =============================================================================
# STEP 2 — MIXED MODELS (trial-level)
# =============================================================================
# Contrasts:
#   pronoun  -> K1 (o vs {pro, kendisi}), K2 (pro vs kendisi)
#   order, antecedent -> sum coding (+/- 0.5)
K_pron <- cbind(
  K1 = c(pro = -1/3, o = 2/3,  kendisi = -1/3),
  K2 = c(pro =  1/2, o = 0,    kendisi = -1/2)
)
contrasts(d$pronoun)    <- K_pron
contrasts(d$order)      <- matrix(c(-0.5, 0.5), 2, 1,
                                  dimnames = list(NULL, "fwd_vs_cat"))
contrasts(d$antecedent) <- matrix(c(-0.5, 0.5), 2, 1,
                                  dimnames = list(NULL, "subj_vs_obj"))

# -- 2a. Primary: cumulative-link mixed model (ordinal) --
cat("\n=== STEP 2a: clmm (ordinal mixed model) ===\n")
m_clmm <- tryCatch(
  clmm(rating_o ~ pronoun * order * antecedent +
         (1 | participant) + (1 | item_id),
       data = d, link = "logit"),
  error = function(e) { message("clmm failed: ", conditionMessage(e)); NULL }
)
if (!is.null(m_clmm)) {
  print(summary(m_clmm))
  cat("\n--- LRT for each fixed effect (drop1) ---\n")
  print(drop1(m_clmm, test = "Chi"))
}

# -- 2b. Robustness: linear mixed model (Gaussian) --
cat("\n=== STEP 2b: lmer (Gaussian robustness) ===\n")
m_lmer <- lmer(rating ~ pronoun * order * antecedent +
                 (1 | participant) + (1 | item_id),
               data = d, REML = TRUE)
print(summary(m_lmer))
cat("\n--- Type-III ANOVA (Satterthwaite) ---\n")
print(anova(m_lmer, type = 3))

# Pick the model emmeans will use downstream
USE <- if (!is.null(m_clmm)) m_clmm else m_lmer
use_mode <- if (!is.null(m_clmm)) "latent" else NULL
em_args <- function(spec, by = NULL) {
  args <- list(USE, specs = spec)
  if (!is.null(by)) args$by <- by
  if (!is.null(use_mode)) args$mode <- use_mode
  do.call(emmeans, args)
}

# =============================================================================
# STEP 3 — PLANNED COMPARISONS (emmeans, Holm-adjusted)
# =============================================================================
cat("\n=== STEP 3: planned comparisons (Holm) — using ",
    ifelse(!is.null(m_clmm), "clmm", "lmer"), " ===\n", sep = "")

# (i) Antecedent effect (subject - object) WITHIN each pronoun
cat("\n(i) Antecedent (subject - object) within each pronoun:\n")
em_i <- em_args(~ antecedent, by = "pronoun")
print(contrast(em_i, method = "revpairwise", adjust = "holm"))

# (ii) Congruency effects via a re-specified model
m_cong <- lmer(rating ~ pronoun * congruency + order +
                 (1 | participant) + (1 | item_id),
               data = d, REML = TRUE)
cat("\n(ii) Congruency (congruent - incongruent), overall:\n")
em_cong_all <- emmeans(m_cong, ~ congruency)
print(contrast(em_cong_all, method = "revpairwise", adjust = "holm"))

cat("\n(ii) Congruency within each pronoun:\n")
em_cong_byp <- emmeans(m_cong, ~ congruency | pronoun)
print(contrast(em_cong_byp, method = "revpairwise", adjust = "holm"))

# (iii) K1, K2 pronoun contrasts
cat("\n(iii) K1 = o vs {pro, kendisi}; K2 = pro vs kendisi\n")
em_pron <- em_args(~ pronoun)
print(contrast(em_pron, list(
  K1 = c(`pro` = -1/3, `o` = 2/3, `kendisi` = -1/3),
  K2 = c(`pro` =  1/2, `o` = 0,   `kendisi` = -1/2)
), adjust = "holm"))

# (iv) Order, and antecedent within order x pronoun
cat("\n(iv) Order (forward - cataphora):\n")
em_ord <- em_args(~ order)
print(contrast(em_ord, method = "revpairwise", adjust = "holm"))

cat("\n(iv) Antecedent (subject - object) within order x pronoun:\n")
em_oxa <- em_args(~ antecedent, by = c("order", "pronoun"))
print(contrast(em_oxa, method = "revpairwise", adjust = "holm"))

# =============================================================================
# STEP 4 — PLOTS
# =============================================================================
plot_data <- d %>%
  group_by(pronoun, order, antecedent) %>%
  summarise(mean = mean(rating),
            se   = sd(rating) / sqrt(n()),
            lo   = mean - 1.96 * se,
            hi   = mean + 1.96 * se,
            .groups = "drop")

p1 <- ggplot(plot_data,
             aes(x = antecedent, y = mean, color = pronoun, group = pronoun)) +
  geom_point(size = 3) +
  geom_line(aes(linetype = pronoun), linewidth = 0.7) +
  geom_errorbar(aes(ymin = lo, ymax = hi), width = 0.1) +
  facet_wrap(~ order) +
  scale_y_continuous(breaks = 1:7, limits = c(1, 7)) +
  labs(title = "Mean rating by pronoun x antecedent, faceted by order",
       subtitle = "Error bars: 95% CI",
       y = "Rating (1 = hic dogru degil, 7 = cok dogru)",
       x = "Antecedent") +
  theme_minimal(base_size = 13)

ggsave(file.path(OUT_DIR, "interaction_pronoun_x_antecedent.png"),
       p1, width = 9, height = 5, dpi = 150)

cong_data <- d %>%
  group_by(pronoun, congruency) %>%
  summarise(mean = mean(rating),
            se   = sd(rating) / sqrt(n()),
            .groups = "drop")

p2 <- ggplot(cong_data, aes(x = pronoun, y = mean, fill = congruency)) +
  geom_col(position = position_dodge(0.8), width = 0.7) +
  geom_errorbar(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se),
                position = position_dodge(0.8), width = 0.15) +
  scale_y_continuous(breaks = 1:7) +
  labs(title = "Congruency effect by pronoun",
       subtitle = "Error bars: 95% CI",
       y = "Mean rating", x = "Pronoun") +
  theme_minimal(base_size = 13)

ggsave(file.path(OUT_DIR, "congruency_by_pronoun.png"),
       p2, width = 8, height = 5, dpi = 150)

cat("\n=== Done. Plots saved to '", OUT_DIR, "/'. ===\n", sep = "")
cat("Files: interaction_pronoun_x_antecedent.png, congruency_by_pronoun.png\n")
